export const GENRES = [
    "Fiction",
    "Non-fiction",
    "Fantasy",
    "Science Fiction",
    "Mystery",
    "Horror",
    "Romance",
    "Thriller",
    "Historical",
    "Biography",
    "Autobiography",
    "Self-help",
    "Travel",
    "Guide",
    "Poetry",
    "Drama",
    "Satire",
    "Anthology",
    "Encyclopedia",
    "Dictionary",
    "Comic",
    "Art",
    "Cookbook",
]
